pipelines:
  MovieSurferPipe:
    group: applications
    materials:
      mygit:
        git: https://github.com/sebradloff/movie-surfer.git
    stages:
      - build:
          jobs:
            build:
              tasks:
                - exec:
                    command: echo
                    arguments:
                      - "Hello World FROM a git server!!"
