pipelines:
  MovieSurferPipe:
    group: applications
    materials:
      mygit:
        git: https://github.com/sebradloff/movie-surfer.git
    stages:
      - Build:
          clean_workspace: true
          jobs:
            Build:
              tasks:
                - exec:
                    command: npm
                    arguments:
                      - install
      - UnitTest:
          jobs:
            UnitTest:
              tasks:
                - exec:
                    command: npm
                    arguments:
                      - test
